# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
# Use Node.js Alpine as base
FROM node:lts-alpine AS build

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and package-lock if present
COPY package.json ./

# Install dependencies
RUN npm install --ignore-scripts

# Copy source files
COPY . .

# Ensure entrypoint script is executable
RUN chmod +x openapi-mcp.js

# Build stage done; create minimal runtime image
FROM node:lts-alpine
WORKDIR /usr/src/app

# Copy dependencies and source from build
COPY --from=build /usr/src/app .

# Default environment variables
ENV OPENAPI_FILE=./openapi.yaml

# Set entrypoint
ENTRYPOINT ["node", "openapi-mcp.js", "run"]
